`timescale 1ns/1ps
// Does a railing preset rail in simulation, on the real Basys 3 RTL?
//
// M28a set out to fix "the shell drops MIDI bytes" and the reproduction (core/sim/tb_midi_drop.v)
// disproved it: 0 bytes lost out of an unpaced 456-byte burst, 0 overwrites of `rxbyte`, and the
// validator paces its CCs 3 ms apart anyway. So the 6/274 presets that rail on Basys 3 and 0/274
// on Tiliqua are still unexplained, and the first thing worth knowing is whether the rail is in
// the RTL at all or only ever appears on the physical board.
//
// This plays one preset through the REAL top.v + engine.v with the exact stimulus
// `validate_hw.capture()` sends (generated by core/sim/gen_midi_stream.py, pacing included) and
// applies the validator's own RAIL test to `sampL`: peak > 0.9 of full scale AND more than 15% of
// consecutive samples jumping by more than half of full scale.
//
// Samples are taken where the shell queues a frame for the host (`pend <- 4`, top.v:345/397) and
// bit 0 is forced low, so this sees exactly what the host decodes -- including the channel-marker
// bit the UART framing steals -- rather than an idealized internal value.
//
//   uv run python core/sim/gen_midi_stream.py Brightness > /tmp/stream.hex
//   $ bash core/sim/run_rail.sh Brightness
//
// It is built with Verilator rather than iverilog: 1.8 s of simulated audio is 180 M clocks,
// which iverilog covers in ~3 hours and Verilator in ~2 minutes. (The tool name is spelled out
// only here, at the start of a line -- a comment beginning with it is read as a lint pragma.)
//
// iverilog has no BUFG primitive, so provide a pass-through stub.
module BUFG(input I, output O); assign O = I; endmodule

module tb_preset_rail;
    reg clk = 1'b0;
    reg rsrx = 1'b1;                 // FT2232 UART, idle high
    wire [15:0] led;
    wire rstx, i2s_bclk, i2s_ws, i2s_sd;

    // midi_din must be driven: an undriven DIN input floats to x and the 31250-baud FSM would
    // latch garbage bytes into the same stream this testbench is driving.
    top dut(.clk(clk), .RsRx(rsrx), .led(led), .RsTx(rstx), .midi_din(1'b1),
            .i2s_bclk(i2s_bclk), .i2s_ws(i2s_ws), .i2s_sd(i2s_sd));

    always #5 clk = ~clk;            // 100 MHz
    localparam integer BAUD = 50;    // matches top.v (2 Mbaud @ 100 MHz)

    task send_byte(input [7:0] b);
        integer i;
        begin
            rsrx = 1'b0; repeat (BAUD) @(posedge clk);            // start bit
            for (i = 0; i < 8; i = i + 1) begin
                rsrx = b[i]; repeat (BAUD) @(posedge clk);        // data bits, LSB first
            end
            rsrx = 1'b1; repeat (BAUD) @(posedge clk);            // stop bit
        end
    endtask

    // ---- capture, as the host sees it ---------------------------------------------------------
    // MAXS covers CAP=1.3 s at 32 kHz with room to spare; overrunning it would silently truncate
    // the statistic, so the run reports the count and the operator can see it did not saturate.
    localparam integer MAXS = 80000;
    reg signed [31:0] cap [0:MAXS-1];
    integer ncap = 0;
    reg capturing = 1'b0;
    reg [2:0] pend_q = 3'd0;
    always @(posedge clk) begin
        pend_q <= dut.pend;
        // top.v loads pend <- 4 on the cycle a finished sample pair is handed to the transmitter.
        if (capturing && dut.pend == 3'd4 && pend_q != 3'd4 && ncap < MAXS) begin
            cap[ncap] = $signed({1'b0, dut.sampL[15:1], 1'b0}) - 32768;   // offset-binary, LSB stolen
            ncap = ncap + 1;
        end
    end

    // ---- tank-state probe -----------------------------------------------------------------------
    // With --prime, a "clean" result only means something if the primer actually left energy in the
    // reverb tank. `fbm` is the comb feedback term (top.v: g*y, read straight out of the tank BRAM),
    // so its peak over the first stretch of the capture is how loud the tank was when the window
    // opened. tankpk near zero => the primer did nothing and the run proves nothing.
    integer tankpk = 0, runpk = 0, fbv, spv;
    integer capclk = 0;
    always @(posedge clk) begin
        spv = dut.sampL - 32768;
        if (spv < 0) spv = -spv;
        if (spv > runpk) runpk = spv;                       // loudest sample anywhere, primer included
        if (capturing) begin
            capclk = capclk + 1;
            if (capclk < 3200000) begin                     // first 32 ms of the window
                fbv = dut.fbm;
                if (fbv < 0) fbv = -fbv;
                if (fbv > tankpk) tankpk = fbv;
            end
        end
    end

    // ---- drive the generated stream -----------------------------------------------------------
    localparam integer MAXW = 8192;
    reg [31:0] prog [0:MAXW-1];
    integer nprog, pc, i, njump, fd;
    integer peak, d;
    real peakf, jumpf;
    reg [1023:0] path;

    initial begin
        for (i = 0; i < MAXW; i = i + 1) prog[i] = 32'hFFFFFFFF;
        if (!$value$plusargs("stream=%s", path)) begin
            $display("ERROR: pass +stream=<file> (see core/sim/gen_midi_stream.py)"); $finish;
        end
        $readmemh(path, prog);
        nprog = 0;
        while (nprog < MAXW && prog[nprog] !== 32'hFFFFFFFF) nprog = nprog + 1;

        repeat (40000) @(posedge clk);       // reset + the 16384-slot BRAM clearing sweep
        for (pc = 0; pc < nprog; pc = pc + 1) begin
            case (prog[pc][31:16])
                16'h0000: send_byte(prog[pc][7:0]);
                16'h0001: repeat (100 * prog[pc][15:0]) @(posedge clk);   // N us at 100 MHz
                16'h0002: begin capturing = 1'b1; ncap = 0; end
                16'h0003: capturing = 1'b0;
            endcase
        end

        // The validator's RAIL test, verbatim: peak > 0.9 && jump fraction > 0.15, both in units
        // of full scale (validate_hw.py:main -- `np.abs(np.diff(L)) > 0.5`).
        peak = 0; njump = 0;
        for (i = 0; i < ncap; i = i + 1) begin
            if (cap[i] > peak)  peak = cap[i];
            if (-cap[i] > peak) peak = -cap[i];
            if (i > 0) begin
                d = cap[i] - cap[i-1];
                if (d < 0) d = -d;
                if (d > 16384) njump = njump + 1;
            end
        end
        peakf = peak / 32768.0;
        jumpf = (ncap > 1) ? njump * 1.0 / (ncap - 1) : 0.0;
        $display("");
        $display("captured %0d samples  peak %.3f  jump%% %.1f  tank %.3f  runpeak %.3f",
                 ncap, peakf, 100.0 * jumpf, tankpk / 32768.0, runpk / 32768.0);
        $display("%s", (peakf > 0.9 && jumpf > 0.15) ? "RAIL: reproduced in simulation"
                                                     : "clean: no rail in simulation");
        // Optional sample dump. "no rail" is only worth believing if the rig is actually playing
        // the preset, so the sweep compares this against engine.render() rather than taking a
        // plausible-looking peak on trust.
        if ($value$plusargs("dump=%s", path)) begin
            fd = $fopen(path, "w");
            for (i = 0; i < ncap; i = i + 1) $fdisplay(fd, "%0d", cap[i]);
            $fclose(fd);
        end
        $finish;
    end
endmodule
